//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID_Log { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Action { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public string Description { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Users Users { get; set; }
    }
}
